/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BacklogIndexImport } from './routes/backlog/index'
import { Route as CategoriesCategoryTitleImport } from './routes/categories/$categoryTitle'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BacklogIndexRoute = BacklogIndexImport.update({
  id: '/backlog/',
  path: '/backlog/',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesCategoryTitleRoute = CategoriesCategoryTitleImport.update({
  id: '/categories/$categoryTitle',
  path: '/categories/$categoryTitle',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/categories/$categoryTitle': {
      id: '/categories/$categoryTitle'
      path: '/categories/$categoryTitle'
      fullPath: '/categories/$categoryTitle'
      preLoaderRoute: typeof CategoriesCategoryTitleImport
      parentRoute: typeof rootRoute
    }
    '/backlog/': {
      id: '/backlog/'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories/$categoryTitle': typeof CategoriesCategoryTitleRoute
  '/backlog': typeof BacklogIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories/$categoryTitle': typeof CategoriesCategoryTitleRoute
  '/backlog': typeof BacklogIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/categories/$categoryTitle': typeof CategoriesCategoryTitleRoute
  '/backlog/': typeof BacklogIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/categories/$categoryTitle' | '/backlog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/categories/$categoryTitle' | '/backlog'
  id: '__root__' | '/' | '/categories/$categoryTitle' | '/backlog/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesCategoryTitleRoute: typeof CategoriesCategoryTitleRoute
  BacklogIndexRoute: typeof BacklogIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesCategoryTitleRoute: CategoriesCategoryTitleRoute,
  BacklogIndexRoute: BacklogIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/categories/$categoryTitle",
        "/backlog/"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/categories/$categoryTitle": {
      "filePath": "categories/$categoryTitle.jsx"
    },
    "/backlog/": {
      "filePath": "backlog/index.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
